language: ruby

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - mysql -e 'create database strano_test'
