development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: yogy_development

test:
  <<: *development
  database: yogy_test

production:
  <<: *development
  adapter: postgresql
  host: ec2-23-23-199-181.compute-1.amazonaws.com 
  username: rwosxxenbibxss
  password: kdAiNul4YvdffGa9azug-o-lbX
  database: dfbm9ktrpg2qpp

